In [2]:
# 日期 取值 集合

# d_list = ['180602', '180603', '180604', '180605', '180606', '180607', '180608', '180609', '180610',\
#           '180611', '180612', '180613', '180614', '180615', '180616', '180617', '180618', '180619', '180620',\
#           '180621', '180622', '180623', '180624', '180625', '180626', '180627', '180628', '180629', '180630',\
#           '180701', '180702', '180703', '180704', '180705', '180706', '180707', '180708', '180709', '180710', \
#           '180711', '180712', '180713', '180714', '180715']

#对7天完整数据做处理

d_list = [ '180709', '180710','180711', '180712', '180713', '180714', '180715']

In [15]:
import pandas as pd
import time

# 替换一些命令前缀
cmd_class = ('perl','touch','sh','python','TDSQLLoader.pl','TDSQLLoaderHis.pl','TDDQCCheck.pl','TDDQCCheckHis.pl','TDDMCheck.pl')
def f_cmdline(cmd):
    if cmd in cmd_class:
        cmd = cmd.replace('TDSQLLoaderHis','TDSQLLoader')
        cmd = cmd.replace('TDDQCCheckHis','TDDQCCheck')
        return cmd
    elif cmd =='':
        return 'cmd_none'
    else:
        return 'cmd_other'
def f_s(s):
    return s[1:]
def f_d(s):
    
    return s[2:8]

### ajob表__处理   由于这批次分隔符不同，和其他程序有点区别

In [27]:
#  对原始文件过滤了 || 转出成csv文件

In [44]:
# i = 0
# #f_w = open(r'E:\aevt\VIEW_AJOB_TMP_20180730.csv','w',encoding='utf-8')
# f_w = open(r'E:\aevt\VIEW_AJOB_TMP_20180730.csv','w')

# with open(r'E:\aevt\VIEW_AJOB_TMP_20180730_000AH000.DAT') as file:
#     for line in file:
        
#         line = line.split('||')
#         del line[6]
#         line = ','.join(line)
# #         i = i+1
# #         if i > 6:
# #             break
#         #print(line)
#         f_w.write(line)
# f_w.close()

In [5]:
#可用  2018.10.29
i = 0
#f_w = open(r'E:\aevt\VIEW_AJOB_TMP_20180730.csv','w',encoding='utf-8')
f_w = open(r'E:\aevt\VIEW_AJOB_TMP_20180730.csv','w')

with open(r'E:\aevt\VIEW_AJOB_TMP_20180730_000AH000.DAT') as file:
    for line in file:
        
        line = line.replace(',','')
        line = line.split('||')
        del line[6]
        del line[-1]
        line.append('\n')
        line = ','.join(line)
#         i = i+1
#         if i > 6:
#             break
        #print(line)
        f_w.write(line)
f_w.close()

In [17]:
pd.options.mode.chained_assignment = None  # default='warn'
clums = ('order_id','task_type','job_name','job_id','odate','max_wait','confirm_flag','from_time','to_time','interval'\
,'next_time','priority','cpu_id','max_rerun','avg_runtime','status','state','delete_flag','start_time','end_time'\
,'rerun_counter','cmdline','cyclic','nodegroup','order_table','order_time','avg_start_time','cpu_time',\
 'prev_odate_rerun_counter','v_date','del_none')

chunk = pd.read_csv(r'E:\aevt\VIEW_AJOB_TMP_20180730.csv',header=None,delimiter=',',error_bad_lines=False)


del chunk[22]

print(len(clums))
print(len(chunk.columns))
chunk.columns = clums

del chunk['del_none']

chunk['order_time'] = chunk['order_time'].apply(str)
chunk['v_date'] = chunk['v_date'].apply(str)

chunk['order_d'] = chunk['order_time'].apply(f_d)
chunk['server'] = chunk['v_date'].apply(lambda x:x[6:10])
chunk['v_date'] = chunk['v_date'].apply(lambda x:x[:6])

chunk['cmdline'] = chunk['cmdline'].apply(f_cmdline)

print(chunk.head())

c:\program files\python3\lib\site-packages\IPython\core\interactiveshell.py:2728: DtypeWarning: Columns (8) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

31
31
  order_id    task_type                                           job_name  \
0    0vfpd          Job     LD_CDM_1_T_HTDW_ACOC_ACOC_ITF_CRM_CLTMONTHBACD
1    1fjxc  SMART Table                                        DXP_TS_HEES
2    0x9up      Command          SYS_FS_ACOC_P_ACOC_RI_JGG_GRP_CUST_DTL_SR
3    1jl9c          Job  DGW_BDDDB_BDD_SP_E_QATBLSTS_UPD_V1_UNLK_DFC26C...
4    1h482      Command              FW_LD_TDW_1_F_HCGC_TTG_DDXX_860000007

      job_id   odate  max_wait  confirm_flag  from_time to_time interval  \
0  1928981.0  180701        20             0        NaN     NaN   00020M
1        NaN  180707        30             0        NaN     NaN   00001M
2     9044.0  180701        20             0        NaN     NaN   00005M
3        NaN  180708         1             0        NaN     NaN   00005M
4        NaN  180707         2             0        NaN     NaN   00005M

    ...    cyclic     nodegroup           order_table      order_time  \
0   ...         0  GRP_DS_AGENT   DXP_LD_CDM_HCOC_PFM  20180701000142
1   ...         0           NaN           DXP_TS_HEES  20180707000145
2   ...         1  GRP_FS_AGENT  DXP_EX_HTDW_ACOC_PFM  20180701000142
3   ...         0  GRP_DB_AGENT          LV34_DGW_BDD  20180708000151
4   ...         1  GRP_DS_AGENT  DXP_FW_TDW_HCGC_LU25  20180707000145

   avg_start_time cpu_time prev_odate_rerun_counter  v_date  order_d  server
0        991142.0    12620                      0.0  180709   180701     001
1          2021.0        0                      1.0  180709   180707     001
2        992926.0        0                      0.0  180709   180701     001
3        100102.0        0                      0.0  180709   180708     001
4        154027.0        0                      0.0  180709   180707     001

[5 rows x 32 columns]

In [18]:
print(chunk.tail())

        order_id task_type                                        job_name  \
1840385    1ki32   Command       SYS_FS_LD_OFB_2_P_HFHJ_1_DBO_MF_TRADESEAT
1840386    1ki39   Command    SYS_FS_LD_OFB_2_P_HFHJ_1_DBO_MF_BALANCESHEET
1840387    1ki0j   Command  SYS_FS_LD_OFB_2_P_HFHJ_1_DBO_MF_FUNDNETVALUERE
1840388    1kifs   Command                 SYS_FS_LD_OFB_2_F_HCRP_OMS0011D
1840389    1kj6p   Command    SYS_FS_LD_OFB_2_T_HTDW_SUM_T83_PL_MRGN_INF_S

          job_id   odate  max_wait  confirm_flag  from_time to_time interval  \
1840385  19868.0  180715         2             0        NaN     NaN   00005M
1840386  11348.0  180715         2             0        NaN     NaN   00005M
1840387  32690.0  180715         2             0        NaN     NaN   00005M
1840388  10826.0  180715         2             0        NaN     NaN   00005M
1840389  32234.0  180715         2             0        NaN     NaN   00005M

          ...    cyclic     nodegroup    order_table      order_time  \
1840385   ...         1  GRP_FS_AGENT  OFB_LOAD_BAS1  20180715000028
1840386   ...         1  GRP_FS_AGENT  OFB_LOAD_BAS1  20180715000028
1840387   ...         1  GRP_FS_AGENT  OFB_LOAD_BAS1  20180715000028
1840388   ...         1  GRP_FS_AGENT  OFB_LOAD_BAS1  20180715000028
1840389   ...         1  GRP_FS_AGENT  OFB_LOAD_BAS1  20180715000028

         avg_start_time cpu_time prev_odate_rerun_counter  v_date  order_d  \
1840385         73224.0        1                      NaN  180715   180715
1840386         73221.0        0                      NaN  180715   180715
1840387         72404.0        0                      NaN  180715   180715
1840388         83258.0        0                      NaN  180715   180715
1840389         61804.0        1                      NaN  180715   180715

         server
1840385     003
1840386     003
1840387     003
1840388     003
1840389     003

[5 rows x 32 columns]

In [19]:
#按日期保存 
for d_i in d_list:
    chunk[chunk['order_d']==d_i].to_csv(r'E:\jupyter\CTM\data_src\ajob\ajob_%s_0.txt'%d_i,index=False)

In [7]:
f = open(r'E:\aevt\VIEW_AJOB_TMP_20180730_000AH000.DAT')
reader = pd.read_csv(f, sep='|',header=None)

c:\program files\python3\lib\site-packages\IPython\core\interactiveshell.py:2728: DtypeWarning: Columns (18) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

In [8]:
reader.head()

,0,1,2,3,4,5,6,7,8,9,...,55,56,57,58,59,60,61,62,63,64
0,0vfpd,NaN,Job,NaN,LD_CDM_1_T_HTDW_ACOC_ACOC_ITF_CRM_CLTMONTHBACD,NaN,1928981.0,NaN,180701,NaN,...,NaN,991142.0,NaN,12620,NaN,0.0,NaN,180709001,NaN,NaN
1,1fjxc,NaN,SMART Table,NaN,DXP_TS_HEES,NaN,NaN,NaN,180707,NaN,...,NaN,2021.0,NaN,0,NaN,1.0,NaN,180709001,NaN,NaN
2,0x9up,NaN,Command,NaN,SYS_FS_ACOC_P_ACOC_RI_JGG_GRP_CUST_DTL_SR,NaN,9044.0,NaN,180701,NaN,...,NaN,992926.0,NaN,0,NaN,0.0,NaN,180709001,NaN,NaN
3,1jl9c,NaN,Job,NaN,DGW_BDDDB_BDD_SP_E_QATBLSTS_UPD_V1_UNLK_DFC26C...,NaN,NaN,NaN,180708,NaN,...,NaN,100102.0,NaN,0,NaN,0.0,NaN,180709001,NaN,NaN
4,1h482,NaN,Command,NaN,FW_LD_TDW_1_F_HCGC_TTG_DDXX_860000007,NaN,NaN,NaN,180707,NaN,...,NaN,154027.0,NaN,0,NaN,0.0,NaN,180709001,NaN,NaN

In [11]:
for i in range(1,64,2):
    del reader[i]
    print(i,end=' ')

1 3 5 7 9 11 13 15 17 19 21 23 25 27 29 31 33 35 37 39 41 43 45 47 49 51 53 55 57 59 61 63

In [17]:
reader.tail()

,1,2,3,4,5,6,7,8,9,10,...,24,25,26,27,28,29,30,31,32,33
1840385,1ki32,Command,SYS_FS_LD_OFB_2_P_HFHJ_1_DBO_MF_TRADESEAT,19868.0,180715,2,生成FS的OS作业SYS_FS_LD_OFB_2_P_HFHJ_1_DBO_MF_TRADE...,0,NaN,NaN,...,0,1,GRP_FS_AGENT,OFB_LOAD_BAS1,20180715000028,73224.0,1,NaN,180715003,NaN
1840386,1ki39,Command,SYS_FS_LD_OFB_2_P_HFHJ_1_DBO_MF_BALANCESHEET,11348.0,180715,2,生成FS的OS作业SYS_FS_LD_OFB_2_P_HFHJ_1_DBO_MF_BALAN...,0,NaN,NaN,...,0,1,GRP_FS_AGENT,OFB_LOAD_BAS1,20180715000028,73221.0,0,NaN,180715003,NaN
1840387,1ki0j,Command,SYS_FS_LD_OFB_2_P_HFHJ_1_DBO_MF_FUNDNETVALUERE,32690.0,180715,2,生成FS的OS作业SYS_FS_LD_OFB_2_P_HFHJ_1_DBO_MF_FUNDN...,0,NaN,NaN,...,0,1,GRP_FS_AGENT,OFB_LOAD_BAS1,20180715000028,72404.0,0,NaN,180715003,NaN
1840388,1kifs,Command,SYS_FS_LD_OFB_2_F_HCRP_OMS0011D,10826.0,180715,2,生成FS的OS作业SYS_FS_LD_OFB_2_F_HCRP_OMS0011D,0,NaN,NaN,...,0,1,GRP_FS_AGENT,OFB_LOAD_BAS1,20180715000028,83258.0,0,NaN,180715003,NaN
1840389,1kj6p,Command,SYS_FS_LD_OFB_2_T_HTDW_SUM_T83_PL_MRGN_INF_S,32234.0,180715,2,生成FS的OS作业SYS_FS_LD_OFB_2_T_HTDW_SUM_T83_PL_MRG...,0,NaN,NaN,...,0,1,GRP_FS_AGENT,OFB_LOAD_BAS1,20180715000028,61804.0,1,NaN,180715003,NaN

In [14]:
colms_len = len(reader.columns)
print(colms_len)

33

In [18]:
del reader[33]

In [15]:
reader.columns = (i for i in range(1,34))

### 作业对应资源表处理

In [5]:
#  
#分10份处理数据,10个日期

chunkSize = 100000
clums = ('order_id','resource','quant','v_date')

cls_todo = clums[1:-1]

for i in range(len(d_list)//10+1):
#     if i != 12 :
#         continue
    print(i)
    start = time.time()
    day_i = d_list[i*10:(i+1)*10]
    chunks = [[],[],[],[],[],[],[],[],[],[]]
    
    day_len = len(day_i)
        
    f = open(r'E:\aevt\VIEW_ALNKI_Q_TMP_20180730_000AH000.DAT')
    reader = pd.read_csv(f, sep='|',header=None, iterator=True)
    
    loop = True
    i=0
    while loop:
        try:
            i += 1
            if i%100 == 0:
                print(i,end=' ')
    #             break
            chunk = reader.get_chunk(chunkSize)
            chunk = chunk[[0,1,2,6]]
            chunk.columns = clums
            #chunk['v_date'] = chunk['v_date'].apply(f_s)     
            chunk['server'] = chunk['v_date'].apply(lambda x:x[7:10]) 
            chunk['v_date'] = chunk['v_date'].apply(lambda x:x[1:7]) 
            for k in range(day_len):
                chunks[k].append(chunk[chunk['v_date']==day_i[k]])

        except StopIteration:
            loop = False
            print("Iteration is stopped.")
    
    

    
    for j in range(day_len):
        df = pd.concat(chunks[j], ignore_index=True)
        
        for cl in cls_todo:
            df[cl] = df[cl].apply(f_s)
        df.to_csv(r'E:\jupyter\CTM\data_src\resorce\job_res_num_%s__.csv'%(df['v_date'][0]),index=False)

    end = time.time()
    print('%0.2f s'%(end-start))

0
Iteration is stopped.
19.18 s

### 依赖关系输入表__处理

In [6]:
#condition ——I 
#分10份处理数据,10个日期

chunkSize = 100000
clums = ('order_id','condition','odate','and_or','v_date')

cls_todo = clums[1:-1]

for i in range(len(d_list)//10+1):
#     if i != 12 :
#         continue
    print(i)
    start = time.time()
    day_i = d_list[i*10:(i+1)*10]
    chunks = [[],[],[],[],[],[],[],[],[],[]]
    
    day_len = len(day_i)
        
    f = open(r'E:\aevt\VIEW_ALNKI_P_TMP_20180730_000AH000.DAT')
    reader = pd.read_csv(f, sep='|',header=None, iterator=True)
    
    loop = True
    i=0
    while loop:
        try:
            i += 1
            if i%100 == 0:
                print(i,end=' ')
    #             break
            chunk = reader.get_chunk(chunkSize)
            chunk = chunk[[0,1,2,3,6]]
            chunk.columns = clums
            #chunk['v_date'] = chunk['v_date'].apply(f_s)     
            chunk['server'] = chunk['v_date'].apply(lambda x:x[7:10]) 
            chunk['v_date'] = chunk['v_date'].apply(lambda x:x[1:7]) 
            for k in range(day_len):
                chunks[k].append(chunk[chunk['v_date']==day_i[k]])

        except StopIteration:
            loop = False
            print("Iteration is stopped.")
    
    for j in range(day_len):
        df = pd.concat(chunks[j], ignore_index=True)
        
        for cl in cls_todo:
            df[cl] = df[cl].apply(f_s)
            
        df['up'] = df['condition'].apply(lambda x:x.split('-TO-')[0])
        df['down'] = df['condition'].apply(lambda x:x.split('-TO-')[-1])
        del df['condition']
        df.to_csv(r'E:\jupyter\CTM\data_src\condition_i/conditin_i_%s__.csv'%(df['v_date'][0]),index=False)

    end = time.time()
    print('%0.2f S'%(end-start))

0
Iteration is stopped.
19.27 S

### 依赖关系输出表__处理

In [7]:
#condition ——O
#分10份处理数据,10个日期
chunkSize = 100000
clums = ('order_id','condition','odate','sign','v_date')

cls_todo = clums[1:-1]

for i in range(len(d_list)//10+1):
#     if i != 12 :
#         continue
    print(i)
    start = time.time()
    day_i = d_list[i*10:(i+1)*10]
    chunks = [[],[],[],[],[],[],[],[],[],[]]
    
    day_len = len(day_i)
        
    f = open(r'E:\aevt\VIEW_ALNKO_P_TMP_20180730_000AH000.DAT')
    reader = pd.read_csv(f, sep='|',header=None, iterator=True)
    
    loop = True
    i=0
    while loop:
        try:
            i += 1
            if i%100 == 0:
                print(i,end=' ')
    #             break
            chunk = reader.get_chunk(chunkSize)
            chunk = chunk[[0,1,2,3,5]]
            chunk.columns = clums
            #chunk['v_date'] = chunk['v_date'].apply(f_s）
            chunk['server'] = chunk['v_date'].apply(lambda x:x[7:10]) 
            chunk['v_date'] = chunk['v_date'].apply(lambda x:x[1:7])
            for k in range(day_len):
                chunks[k].append(chunk[chunk['v_date']==day_i[k]])

        except StopIteration:
            loop = False
            print("Iteration is stopped.")
    
    

    
    for j in range(day_len):
        df = pd.concat(chunks[j], ignore_index=True)
        
        for cl in cls_todo:
            df[cl] = df[cl].apply(f_s)
            
        df['up'] = df['condition'].apply(lambda x:x.split('-TO-')[0])
        df['down'] = df['condition'].apply(lambda x:x.split('-TO-')[-1])
        del df['condition']
        df.to_csv(r'E:\jupyter\CTM\data_src\condition_o\conditin_o_%s__.csv'%(df['v_date'][0]),index=False)

    end = time.time()
    print('%0.2f S'%(end-start))

0
Iteration is stopped.
39.18 S

### 事件表__处理

In [9]:
##ALNKI_Q_TMP_  事件表
#分10份处理数据,10个日期

chunkSize = 100000
clums = ('evt_time','new_value','old_value','order_id','v_date')

cls_todo = clums[0:-1]

for i in range(len(d_list)//5+1):
#     if i != 12 :
#         continue
    print(i)
    start = time.time()
    day_i = d_list[i*5:(i+1)*5]
    chunks = [[],[],[],[],[],[],[],[],[],[]]
    
    day_len = len(day_i)
        
    f = open(r'E:\aevt\VIEW_AEVT_TMP_20180730_000AH000.DAT')
    reader = pd.read_csv(f, sep='|',header=None, iterator=True)
    
    loop = True
    i=0
    while loop:
        try:
            i += 1
            if i%100 == 0:
                print(i,end=' ')
    #             break
            chunk = reader.get_chunk(chunkSize)
            chunk = chunk[[1,3,4,5,8]]
            chunk.columns = clums
            #chunk['v_date'] = chunk['v_date'].apply(f_s)
            
            chunk['server'] = chunk['v_date'].apply(lambda x:x[7:10]) 
            chunk['v_date'] = chunk['v_date'].apply(lambda x:x[1:7]) 
            chunk['evt_time'] = chunk['evt_time'].apply(lambda x:x[:-7])
            for k in range(day_len):
                chunks[k].append(chunk[chunk['v_date']==day_i[k]])

        except StopIteration:
            loop = False
            print("Iteration is stopped.")
    
    

    
    for j in range(day_len):
        df = pd.concat(chunks[j], ignore_index=True)
        
        for cl in cls_todo:
            df[cl] = df[cl].apply(f_s)
        
        df.to_csv(r'E:\jupyter\CTM\data_src\evet\evet_%s.csv'%(df['v_date'][0]),index=False)

    end = time.time() 
    print('%0.2f mintue'%((end-start)/60))

0
100 200 300 Iteration is stopped.
3.97 mintue
1
100 200 300 Iteration is stopped.
2.54 mintue